-- Time-series aggregate view of Copilot response confidence scores grouped by day.
CREATE OR REPLACE VIEW V_ANALYTICS_CONFIDENCE_TRENDS AS
SELECT 
    DATE_TRUNC('day', CREATED_AT) AS METRIC_DATE,
    DEPARTMENT_ID,
    COUNT(*) AS TOTAL_RESPONSES,
    AVG(CONFIDENCE_SCORE) AS AVG_CONFIDENCE_SCORE,
    MIN(CONFIDENCE_SCORE) AS MIN_CONFIDENCE_SCORE,
    MAX(CONFIDENCE_SCORE) AS MAX_CONFIDENCE_SCORE
FROM COPILOT_INTERACTIONS
GROUP BY DATE_TRUNC('day', CREATED_AT), DEPARTMENT_ID;
