-- View calculating confusion metrics (high escalation rate or high clarification requests per session).
CREATE OR REPLACE VIEW V_ANALYTICS_CONFUSING_PROCEDURES AS
SELECT 
    s.SOP_ID,
    k.TITLE AS SOP_TITLE,
    k.DEPARTMENT_ID,
    COUNT(DISTINCT s.SESSION_ID) AS TOTAL_SESSIONS,
    COUNT(DISTINCT CASE WHEN s.STATUS = 'ESCALATED' OR s.CLARIFICATION_COUNT >= 3 THEN s.SESSION_ID END) AS CONFUSING_SESSIONS,
    ROUND(
        COUNT(DISTINCT CASE WHEN s.STATUS = 'ESCALATED' OR s.CLARIFICATION_COUNT >= 3 THEN s.SESSION_ID END) * 100.0 / NULLIF(COUNT(DISTINCT s.SESSION_ID), 0), 
        2
    ) AS CONFUSION_RATE_PCT,
    AVG(s.CLARIFICATION_COUNT) AS AVG_CLARIFICATION_REQUESTS
FROM WORKFLOW_SESSIONS s
JOIN KNOWLEDGE_DOCUMENTS k ON s.SOP_ID = k.DOCUMENT_ID
GROUP BY s.SOP_ID, k.TITLE, k.DEPARTMENT_ID;
