-- View measuring platform adoption metrics grouped by department.
CREATE OR REPLACE VIEW V_ANALYTICS_DEPARTMENT_ADOPTION AS
SELECT 
    u.DEPARTMENT_ID,
    COUNT(DISTINCT u.USER_ID) AS TOTAL_ENROLLED_USERS,
    COUNT(DISTINCT c.USER_ID) AS ACTIVE_COPILOT_USERS,
    COUNT(c.INTERACTION_ID) AS TOTAL_INTERACTIONS,
    ROUND(
        COUNT(DISTINCT c.USER_ID) * 100.0 / NULLIF(COUNT(DISTINCT u.USER_ID), 0), 
        2
    ) AS ADOPTION_RATE_PCT
FROM USERS u
LEFT JOIN COPILOT_INTERACTIONS c ON u.USER_ID = c.USER_ID
GROUP BY u.DEPARTMENT_ID;
