-- View summarizing human escalation events by department, SOP, and root cause reason.
CREATE OR REPLACE VIEW V_ANALYTICS_ESCALATIONS AS
SELECT 
    e.ESCALATION_ID,
    e.SESSION_ID,
    e.USER_ID,
    u.DEPARTMENT_ID,
    e.SOP_ID,
    k.TITLE AS SOP_TITLE,
    e.REASON AS ESCALATION_REASON,
    e.STATUS AS ESCALATION_STATUS,
    e.CREATED_AT
FROM ESCALATIONS e
LEFT JOIN USERS u ON e.USER_ID = u.USER_ID
LEFT JOIN KNOWLEDGE_DOCUMENTS k ON e.SOP_ID = k.DOCUMENT_ID;
