-- View materializing the top queried operational topics based on Copilot sessions.
CREATE OR REPLACE VIEW V_ANALYTICS_FAQS AS
SELECT 
    QUERY_TOPIC,
    DEPARTMENT_ID,
    COUNT(*) AS QUERY_COUNT,
    AVG(CONFIDENCE_SCORE) AS AVG_CONFIDENCE,
    MAX(CREATED_AT) AS LAST_QUERIED_AT
FROM COPILOT_INTERACTIONS
WHERE QUERY_TOPIC IS NOT NULL
GROUP BY QUERY_TOPIC, DEPARTMENT_ID;
