-- View aggregating SOP execution counts, unique active users, and mean completion duration.
CREATE OR REPLACE VIEW V_ANALYTICS_SOP_USAGE AS
SELECT 
    w.SOP_ID,
    k.TITLE AS SOP_TITLE,
    k.DEPARTMENT_ID,
    COUNT(DISTINCT w.SESSION_ID) AS TOTAL_EXECUTIONS,
    COUNT(DISTINCT w.USER_ID) AS UNIQUE_USERS,
    AVG(DATEDIFF('minute', w.STARTED_AT, COALESCE(w.COMPLETED_AT, CURRENT_TIMESTAMP()))) AS AVG_COMPLETION_MINUTES,
    MAX(w.UPDATED_AT) AS LAST_USED_AT
FROM WORKFLOW_SESSIONS w
JOIN KNOWLEDGE_DOCUMENTS k ON w.SOP_ID = k.DOCUMENT_ID
GROUP BY w.SOP_ID, k.TITLE, k.DEPARTMENT_ID;
